#!/bin/bash

# ./compute deploy production bartnet latest

PLAY=$1
ENVIRONMENT=$2
SERVICES=$3
IMAGE_TAG=$4

function usage {
  echo "usage: $0 [playbook] [environment] [services] [image-tag]"
}

if [ "${PLAY}x" = "x" ]; then
  usage
  exit 1
fi

if [ "${ENVIRONMENT}x" = "x" ]; then
  usage
  exit 1
fi

if [ "${SERVICES}x" = "x" ]; then
  usage
  exit 1
fi

ARGS="-e environment=$ENVIRONMENT -f 1 -vvvv"

ansible-playbook "playbooks/${PLAY}.yml" $ARGS
