#!/bin/bash

# ./run [playbook] [extra args]

PLAYBOOK=$1
shift
ARGS=$@

if [ "${PLAYBOOK}x" = "x" ]; then
  echo "usage: $0 [playbook] [extra args]"
  exit 1
fi

docker run --rm \
-e AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION} \
-e AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} \
-e AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} \
opsee-ansible playbooks/${PLAYBOOK}.yml $ARGS
